<?php

    function order_form_menu() {
        $items = array();
        $items['order_form'] = array (
            'title' => 'Order form',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('order_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
    );
    $items['order_success_page'] = array (
        'title' => 'Order confirmation',
        'page callback' => 'order_success_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function order_form() {
    $form['type_options'] = array(
        '#type' => 'value',
        '#value' => array(
            'NONE' => t('--- SELECT ---'),
            'Stumptown Hair Bender' => t('Stumptown Hair Bender'),
            'Batman Blend' => t('Batman Blend'),
            'Treehouse Blend' => t('Treehouse Blend'),
        )
    );
    $form['type'] = array(
        '#title' => 'type',
        '#type' => 'select',
        '#description' => t('Please choose the type of coffee you want to order'),
        '#options' => $form['type_options']['#value'],
    );
    $form['quantity'] = array(
        '#title' => 'quantity',
        '#type' => 'textfield',
        '#description' => t('Enter quantity'),
    );
    $form['address'] = array(
        '#title' => 'address',
        '#type' => 'textfield',
        '#description' => t('Shipping address'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Enter order',
    );

    return $form;
}

function order_form_submit($form, &$form_state) {
    var_dump($form_state);
    $type  = $form_state['values']['type'];
    $quantity  = $form_state['values']['quantity'];
    $address  = $form_state['values']['address'];
    $_SESSION['order_confirmation']  = '<h2>Order Details:</h2> <br> <h4>Type:'. $type .'</h4><br>
    <h4>Address:'. $address .'</h4><br>
    <h4>Quantity:'. $quantity .'</h4><br>';
    $form_state['redirect'] = 'order_success_page';
}

function order_success_page() {
    $confirmation = $_SESSION['order_confirmation'];
    return "<br>" . $confirmation;
}
