<?php

function greeting_menu() {
    $items = array();
    $items['hello_user_message'] = array(
        'title' => 'Hello!',
        'page callback' => 'hello_user_message',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['goodbye_user_message'] = array(
        'title' => 'Goodbye Friend!',
        'page callback' => 'goodbye_user_message',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function hello_user_message() {
    GLOBAL $user;
    $roles = $user->roles;
    if (count($roles) > 1) {
        return "<p>Hello admin, thanks for logging in</p>";
    } else {
        return "<p>Hello registered user, thanks for logging in!</p>";
    }
}

function goodbye_user_message() {
    return "<p>Goodbye, thanks for stopping by!</p>";
}

function greeting_user_login() {
    $_GET['destination'] = 'hello_user_message';
}

function greeting_user_logout() {
  $_GET['destination'] = 'goodbye_user_message';
}
