<?php

function greeting_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['goodbye'] = array(
        'title' => 'Goodbye Friend!',
        'page callback' => 'say_goodbye',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}
// Note: Use MENU_CALLBACK (rather than MENU_NORMAL_ITEM) to create a function that does not show up in a menu, such as a 'success' page after a form submission.

function say_hello() {
    return '<p>Hello my dear friend!</p>';
}

function say_goodbye() {
    return '<p>Goodbye my dear friend!</p>';
}

function greeting_user_login() {
  $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout() {
  $_GET['destination'] = 'goodbye';
}
