<?php

function hello_user_menu() {
    $items = array();
    $items['hello_user'] = array(
        'title' => 'Hello new user!',
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['comment_confirmation'] = array(
        'title' => 'Comment submitted!',
        'page callback' => 'comment_confirmation',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['comment_deleted'] = array(
        'title' => 'Comment deleted!',
        'page callback' => 'comment_deleted',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['comment_updated'] = array(
        'title' => 'Comment updated!',
        'page callback' => 'comment_updated',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function welcome_user() {
    return "
        <h1>Welcome to Cameron's Coffee!</h1>
        <p>As a registered user, you will have access to our special events and discounts!</p>
    ";
}

function hello_user_user_insert() {
    $_GET['destination'] = 'hello_user';
}

function comment_confirmation() {
    return "<h1>Success</h1>";
}

function comment_deleted() {
    return "<h1>Comment has been deleted</h1>";
}

function comment_updated() {
    return "<h1>Comment has been updated</h1>";
}

function hello_user_comment_insert() {
    $_GET['destination'] = 'comment_confirmation';
}

function hello_user_comment_delete() {
    $_GET['destination'] = 'comment_deleted';
}

function hello_user_comment_update() {
    $_GET['destination'] = 'comment_updated';
}
